### ISSUE TITLE
close(fd) without specific check for fd

### ISSUE THREAD

**Issue by ghost** [Theldus/Tiny2FA#1]
sorry if this is an inappropriate question.

i was wondering will [this line](https://github.com/Theldus/Tiny2FA/blob/6b1136d5e0947ef2332dca13002bc5387b6c090c/src/tiny2fa.c#L69) cause any trouble?

thanks in advance

**Comment by Theldus** [comment]
Hi @D0x45,
Yes, you're completely right.
Commit [b6fb16f](https://github.com/Theldus/Tiny2FA/commit/b6fb16f26d0e4f0b7ff5efe039d6e19bdc8370ad) fixes this, thanks for spotting this =).
